- name: Add New User
  user:
    name: "{{ ssh_user }}"
    shell: /bin/bash
  tags: ['never', 'add_user']

- name: Grant SSH access
  authorized_key:
    user: "{{ ssh_user }}"
    state: present
    key: "{{ lookup('file', '../../public-keys/{{ ssh_user }}/{{user}}.id_rsa.pub') }}"
  tags:
    - always